# MONGODB (MongoProperties)
spring.data.mongodb.uri=mongodb://localhost:27017/OnlineShopping
server.port=8083
# Logging Properties
logging.level.root=WARN
logging.level.org.springframework.web=INFO
logging.level.com.deloitte.shoppingcart=DEBUG

# Logging pattern for file
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

logging.file=logs/OnlineShopping.log